### ISSUE TITLE
Creation of dynamic property PHPExcel_Calculation::$_debugLog is deprecated

### ISSUE THREAD

**Issue by berberon** [DisWEBru/phpexcel#1]
Creation of dynamic property PHPExcel_Calculation::$_debugLog is deprecated in /phpexcel-1.0.6/Classes/PHPExcel/Calculation.php on line 2077

**Comment by berberon** [comment]
[12-Apr-2024 15:21:12 Asia/Jerusalem] PHP Deprecated:  Creation of dynamic property PHPExcel_Calculation::$_debugLog is deprecated in /phpexcel-1.0.6/Classes/PHPExcel/Calculation.php on line 2077
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Return type of PHPExcel_WorksheetIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /phpexcel-1.0.6/Classes/PHPExcel/WorksheetIterator.php on line 76
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Return type of PHPExcel_WorksheetIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /phpexcel-1.0.6/Classes/PHPExcel/WorksheetIterator.php on line 94
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Return type of PHPExcel_WorksheetIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /phpexcel-1.0.6/Classes/PHPExcel/WorksheetIterator.php on line 86
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Return type of PHPExcel_WorksheetIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /phpexcel-1.0.6/Classes/PHPExcel/WorksheetIterator.php on line 104
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Return type of PHPExcel_WorksheetIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /phpexcel-1.0.6/Classes/PHPExcel/WorksheetIterator.php on line 66
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, true given in /phpexcel-1.0.6/Classes/PHPExcel/Writer/Excel2007/Worksheet.php:771
Stack trace:
#0 /phpexcel-1.0.6/Classes/PHPExcel/Writer/Excel2007/Worksheet.php(92): PHPExcel_Writer_Excel2007_Worksheet->writeAutoFilter(Object(PHPExcel_Shared_XMLWriter), Object(PHPExcel_Worksheet))
#1 /phpexcel-1.0.6/Classes/PHPExcel/Writer/Excel2007.php(295): PHPExcel_Writer_Excel2007_Worksheet->writeWorksheet(Object(PHPExcel_Worksheet), Array, false)
#2 /Check.php(242): PHPExcel_Writer_Excel2007->save('/Alerts_2024-04-12.xlsx')
#3 {main}
  thrown in /phpexcel-1.0.6/Classes/PHPExcel/Writer/Excel2007/Worksheet.php on line 771
[12-Apr-2024 15:21:18 Asia/Jerusalem] PHP Deprecated:  Creation of dynamic property PHPExcel_Calculation::$_debugLog is deprecated in /phpexcel-1.0.6/Classes/PHPExcel/Calculation.php on line 2077

**Comment by DisWEBru** [comment]
@berberon Thank you. Fixed in release 2.0.0
