### ISSUE TITLE
Implicit conversion from float {Number} to int loses precision in PHPExcel/Writer/Excel2007/StringTable.php

### ISSUE THREAD

**Issue by redbrad0** [DisWEBru/phpexcel#9]
I am unable to figure out this issue. When I run something like SetCellValueByColumnAndRow('1', '1', '46283.46') I am given the error about Implicit conversion. I have even tried to set the format of the cell to $###0.00;[Red](###0.00) before setting the value and still getting the same error. Any ideas what could be causing this?

[/PHPExcel/Writer/Excel2007/StringTable.php][line:64] backTrace=#0 /PHPExcel/Writer/Excel2007.php(204):
PHPExcel_Writer_Excel2007_StringTable->createStringTable()
#1 Reports.class.php(563): PHPExcel_Writer_Excel2007->save()
#2 Reports.class.php(1868): Reports->build_Report()
#3 open_report.php(509): Reports->process_Report()
#4 {main}

**Comment by redbrad0** [comment]
I am not sure if this is the best fix but it at least got rid of the error for me. I added if its not a string the to convert to a int. If there is a better way to handle it let me know.

                $cell = $pSheet->getCell($cellID);
                $cellValue = $cell->getValue();
                if (!is_string($cellValue))	{
                	$cellValue = (int)$cellValue;
                }

**Comment by DisWEBru** [comment]
@redbrad0 Thank you. Fixed in release 2.0.4
